"""Facility Management module schemas and standard context fields configuration."""

# Single source of truth for the facility management module schemas.
# The explanations naturally contain the synonyms needed for matching.
MODULE_SCHEMAS = {
    "assets": {
        "EquipmentName": "Description, name, or type of the equipment, asset, device, machine, or unit",
        "AssetTagNo": "Unique tag or identifier of the asset",
        "LocalityName": "Locality, area, location, region, or zone name",
        "AssetBarcode": "Barcode or scan number of the asset",
        "DivisionName": "Service division, department, discipline, type, or responsible team",
        "DisciplineName": "Discipline or specific category of the asset (e.g. FCU, motorized)",
        "PriorityName": "Priority level, urgency, or critical status of the asset",
        "AssetTypeName": "Type of asset classification (e.g. Movable, Fixed)",
        "ConditionName": "Physical condition of the asset (e.g. Good, Bad, Fair)",
        "StatusName": "Current status of the asset (e.g. Online, Offline)",
        "MakeName": "Manufacturer or brand name of the asset",
        "ModelName": "Model number or model name of the asset",
        "BuildingName": "Building name, tower, property, site, or location",
        "FloorName": "Floor level or floor name where the asset is located",
        "SpotName": "Specific spot, room, area, or location details of the asset"
    },
    "bdm": {
        "ComplaintNo": "Unique complaint number, ID, no, or reference",
        "LocalityName": "Locality, area, location, region, or zone name",
        "BuildingName": "Building name, tower, property, site, or location",
        "FloorName": "Floor level or floor name where the complaint is reported",
        "SpotName": "Specific spot, room, or exact location of the issue",
        "DivisionName": "Service division, department, discipline, type, equipment type, or responsible team",
        "ServiceTypeName": "Service type name under maintenance",
        "ComplaintTypeName": "Type of complaint (e.g. Service Request, Emergency)",
        "ComplaintModeName": "How the complaint was received (e.g. By Mail, Phone, Portal)",
        "ComplaintNatureName": "Description, nature, issue, problem, or repeated complaint",
        "AnalysisTechName": "Technician, tech, staff, personnel, engineer, or workload assigned to analyze the complaint",
        "ExecutionTechName": "Technician, tech, staff, personnel, engineer, or workload assigned to execute the work",
        "ComplainedDateTime": "Date, time, when, raised, or created complaint",
        "AnalysisStartTime": "Analysis start date, time, when, or downtime",
        "AnalysisEndTime": "Analysis end date, time, when, or downtime",
        "ExecutionStartTime": "Execution start date, time, or when",
        "ExecutionEndTime": "Execution end date, time, or when",
        "BDMWOCompletedDate": "Completed date and time of the BDM work order",
        "ResponseTAT": "Response turnaround status, SLA, or TAT",
        "ResolutionTAT": "Resolution turnaround status, SLA, TAT, or window",
        "WoStatus": "Current status of work order (open or closed)",
        "StageName": "Stage name or detailed process step of the complaint",
        "PriorityName": "Priority level, urgency, or critical status of the complaint",
        "ContractName": "Contract, contractor, or vendor responsible"
    },
    "ppm": {
        "WorkOrder": "Unique PPM work order number, ID, no, or reference",
        "LocalityCode": "Locality code or short abbreviation",
        "LocalityName": "Locality, area, location, region, or zone name",
        "EquipmentName": "Description, name, or type of the equipment, asset, device, machine, or unit under maintenance",
        "AssetTagNo": "Unique tag or identifier of the maintenance asset",
        "DivisionName": "Service division, department, discipline, type, equipment type, or responsible team",
        "DisciplineName": "Discipline name or specific category (e.g. FCU, HVAC)",
        "ContractName": "Contract, contractor, or vendor responsible",
        "BuildingName": "Building name, tower, property, site, or location",
        "FloorName": "Floor level or floor name of maintenance",
        "SpotName": "Specific spot, room, or exact location of maintenance",
        "FrequencyName": "Maintenance frequency (e.g. Monthly, Quarterly, Half-Yearly, Annual)",
        "PPMStageName": "Stage name or detailed process step of the PPM task",
        "PPMStatus": "Current status of the PPM work order (open or closed)",
        "WoDateTime": "Scheduled date, time, or when of the PPM work order",
        "WoCompletedDate": "Date, time, when, or completed date of the work order",
        "PMTechName": "Technician, tech, staff, personnel, engineer, or workload assigned to the planned maintenance task",
        "PMTechStartDateTime": "Start date and time of the PM technician work",
        "PMTechEndDateTime": "End date and time of the PM technician work",
        "PMTechRemarks": "Remarks or comments left by the PM technician",
        "PPMPendingPeriod": "Number of days the PPM task has been pending, overdue, delayed, or in backlog",
        "SLADuration": "SLA duration in days or SLA target window"
    },
    "fa": {
        "RMComplaintNo": "Unique audit or remedial complaint number, ID, no, or reference",
        "RMComplainedDateTime": "Date, time, when the audit complaint was created",
        "ContractName": "Contract, contractor, or vendor responsible",
        "LocalityName": "Locality, area, location, region, or zone name",
        "BuildingName": "Building name, tower, property, site, or location",
        "FloorName": "Floor level or floor name audited",
        "SpotName": "Specific spot, room, or audited location",
        "DivisionName": "Service division, department, discipline, type, or responsible team",
        "FrequencyName": "Audit/inspection frequency (e.g. Monthly, Weekly)",
        "RMStageName": "Current stage of the remedial/audit activity",
        "RMCategoryName": "Category name of the audit/remedial task (e.g. Pest Control)",
        "RMCategorySubName": "Sub-category or detail of the audit task",
        "RMRequestDetailsDesc": "Description or request details of the audit task",
        "PriorityName": "Priority level, urgency, or critical status",
        "RMTechName": "Technician, tech, staff, or inspector assigned",
        "RMTeStartDateTime": "Start date and time of the remedial execution",
        "RMTeEndDateTime": "End date and time of the remedial execution",
        "RMBDMWOCompletedDate": "Completed date and time of the remedial work order",
        "RMMaintenanceHrs": "Maintenance hours or effort spent on the audit/remedial task"
    },
    "sb": {
        "SBRequestNo": "Unique schedule booking request number, ID, no, or reference",
        "LocalityName": "Locality, area, location, region, or zone name",
        "BuildingName": "Building name, tower, property, site, or location",
        "FloorName": "Floor level or floor name of the booking",
        "SpotName": "Cleanliness inspection spot name, location, place, or cleanliness rating",
        "DivisionName": "Service division, department, discipline, type, or responsible team",
        "ServiceTypeName": "Service type name of the booking",
        "SBTypeName": "Type of schedule booking (e.g. Scheduled Service)",
        "SBStatus": "Current status of the schedule booking (e.g. Open, Closed)",
        "SBStageName": "Stage name or detailed process step of the booking",
        "PriorityName": "Priority level, urgency, or critical status",
        "RequestedBy": "Username or person who requested/created the booking",
        "TechName": "Technician, tech, or staff assigned to the booking",
        "BookedDateTime": "Date and time the booking was registered",
        "ScheduledDateTime": "Scheduled date and time of the booking",
        "CompletedDateTime": "Completed date and time of the booking",
        "ContractName": "Contract, contractor, or vendor responsible",
        "Remarks": "Remarks, notes, or descriptions of the booking"
    }
}

STANDARD_CONTEXT_FIELDS = {
    "assets": ["AssetTagNo", "StatusName", "BuildingName", "LocalityName"],
    "bdm": ["ComplaintNo", "WoStatus", "BuildingName", "LocalityName"],
    "ppm": ["WorkOrder", "PPMStatus", "BuildingName", "LocalityName"],
    "fa": ["RMComplaintNo", "RMStageName", "BuildingName", "LocalityName"],
    "sb": ["SBRequestNo", "SBStatus", "BuildingName", "LocalityName"],
}
